--DDL문 CREATE, ALTER, DROP
--오라클 대표 데이터 타입(VARCHAR2 - 가변문자, CHAR - 고정문자, NUMBER - 숫자, DATE - 날짜)

CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2), --자리수가 2자리
    DEPT_NAME VARCHAR2(20), --최대 20바이트, 가변문자형
    DEPT_YN CHAR(1), --1BYTE 고정문자형
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10,3) --총 10자리, 정수부분 7자리, 소수부분 3자리
);

DESC DEPTS2;

INSERT INTO DEPTS2 VALUES(99,'SALES', 'Y', SYSDATE, 3.14);
INSERT INTO DEPTS2 VALUES(99,'SALES', '예', SYSDATE, 3.14); --한글은 2바이트이므로 '예'는 입력 불가

SELECT * FROM DEPTS2;
COMMIT;
--------------------------------------------------------------------------------
--열추가
ALTER TABLE DEPTS2 ADD (DEPT_COUNT NUMBER(3));

--열 이름 변경
ALTER TABLE DEPTS2 RENAME COLUMN DEPT_COUNT TO EMP_COUNT;

--열 수정
ALTER TABLE DEPTS2 MODIFY (EMP_COUNT NUMBER(10));

--열 삭제
ALTER TABLE DEPTS2 DROP COLUMN EMP_COUNT;

DESC DEPTS2;
SELECT * FROM DEPTS2;

--테이블 삭제
DROP TABLE DEPTS2;
--DROP TABLE DEPTS2 CASCADE 제약조건명; -- 제약조건 FK도 삭제, 테이블도 삭제

--------------------------------------------------------------------------------
--제약조건
--열레벨 제약조건(테이블 생성 당시에 열 옆에 적음)
SELECT * FROM USER_CONSTRAINTS;
--제약조건명 생략하고 생성 --제약조건명을 적지 않으면 자동생성된다.
CREATE TABLE DEPTS2 (
    DEPT_NO NUMBER(2)        PRIMARY KEY, 
    DEPT_NAME VARCHAR(20)    NOT NULL,
    DEPT_DATE DATE           DEFAULT SYSDATE, --제약조건은 아니고 컬럼의 기본값
    DEPT_PHONE VARCHAR2(20)  UNIQUE,
    DEPT_BONUS NUMBER(10)    CHECK(DEPT_BONUS > 0),
    LOCA NUMBER(4)           REFERENCES LOCATIONS(LOCATION_ID)--FK REFERENCES 참조테이블(참조컬럼)
);

--제약조건 이름을 지정
CREATE TABLE DEPTS3 (
    DEPT_NO NUMBER(2)        CONSTRAINT DEPT3_PK PRIMARY KEY, 
    DEPT_NAME VARCHAR(20)    CONSTRAINT DEPT3_NAME_NN NOT NULL,
    DEPT_DATE DATE           DEFAULT SYSDATE, --제약조건은 아니고 컬럼의 기본값
    DEPT_PHONE VARCHAR2(20)  CONSTRAINT DEPT3_PHONE_UK UNIQUE,
    DEPT_BONUS NUMBER(10)    CONSTRAINT DEPT3_BONUS_CK CHECK(DEPT_BONUS > 0),
    LOCA NUMBER(4)           CONSTRAINT DEPT3_LOCA_FK REFERENCES LOCATIONS(LOCATION_ID)--FK REFERENCES 참조테이블(참조컬럼)
);

--테이블 레벨 제약조건(슈퍼키나 다중 FK 등 선언이 가능)
CREATE TABLE DEPTS4 (
    DEPT_NO NUMBER(2), 
    DEPT_NAME VARCHAR(20) NOT NULL, --테이블 레벨로 제약이 안됨,
    DEPT_DATE DATE    DEFAULT SYSDATE,--제약조건은 아니고 컬럼의 기본값
    DEPT_PHONE VARCHAR2(20),
    DEPT_BONUS NUMBER(10),
    LOCA NUMBER(4),
    
    CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NO /*, DEPT_NAME */), --슈퍼키 생성
    CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPT_BONUS_CK CHECK (DEPT_BONUS > 0),
    CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS (LOCATION_ID)
);

DESC DEPTS4; 
--개체무결성 (NULL과 중복값을 허용하지 않음) : UNIQUE CONSTRAINT VIOLATED
INSERT INTO DEPTS4 VALUES(10, 'CHARLIE', SYSDATE, '0100000', 10000, 1000);
INSERT INTO DEPTS4 VALUES(10, 'CHARLIE', SYSDATE, '0101111', 10000, 1000);
INSERT INTO DEPTS4 VALUES(20, 'CHARLIE', SYSDATE, '0100000', 10000, 1000);

--참조무결성 (참조테이블의 PK가 아닌 값이 FK에 들어갈 수 없음) : INTEGRITY CONSTRAINT VIOLATED - PARENT KEY NOT FOUND
INSERT INTO DEPTS4 VALUES(20, 'CHARLIE', SYSDATE, '0101111',10000,500); --LOCATIONS의 PK에 500이 없음

--도메인 무결성(값은 컬럼에 정의된 값이어야 한다) : CHECK CONSTRAINT VIOLATED
INSERT INTO DEPTS4 VALUES(30, 'CHARLIE', SYSDATE, '0102222',-1000, 1000);
--DEPT_BONUS는 음수 값 들어갈 수 없음
SELECT * FROM LOCATIONS;

--------------------------------------------------------------------------------
--제약조건을 추가 OR 삭제
 CREATE TABLE DEPTS5 (
    DEPT_NO NUMBER(2), 
    DEPT_NAME VARCHAR(20),
    DEPT_DATE DATE    DEFAULT SYSDATE,--제약조건은 아니고 컬럼의 기본값
    DEPT_PHONE VARCHAR2(20),
    DEPT_BONUS NUMBER(10),
    LOCA NUMBER(4)
);
--제약조건은 수정이 없음
ALTER TABLE DEPTS5 ADD CONSTRAINT DEPT_PK_1 PRIMARY KEY (DEPT_NO);
ALTER TABLE DEPTS5 ADD CONSTRAINT DEPT_PHONE_UK_1 UNIQUE (DEPT_PHONE);
ALTER TABLE DEPTS5 ADD CONSTRAINT DEPT_BONUS_CK_1 CHECK (DEPT_BONUS > 0);
ALTER TABLE DEPTS5 ADD CONSTRAINT DEPT_LOKA_FK_1 FOREIGN KEY (LOCA) REFERENCES LOCATIONS (LOCATION_ID);

--NOT NULL 은 MODIFIY 문장으로 수정을 한다.
ALTER TABLE DEPTS5 MODIFY DEPT_NAME NOT NULL;
--제약조건 삭제
ALTER TABLE DEPTS5 DROP CONSTRAINT DEPT_LOKA_FK_1;
DESC DEPTS5;
--DEPT6는 마우스로 생성하기

--------------------------------------------------------------------------------
