CREATE TABLE GIS_MEMBERS (
    MEMBER_ID VARCHAR2(30) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
    MEMBER_PW VARCHAR2(30) NOT NULL, 
    MEMBER_NAME VARCHAR2(10) NOT NULL,
    MEMBER_BIRTH DATE DEFAULT SYSDATE,
    MEMBER_GRADE VARCHAR2(10) CHECK (MEMBER_GRADE IN ('GOLD', 'SILVER', 'BRONZE'))
    
);


INSERT INTO GIS_MEMBERS VALUES ( 'USER1', 'USERPW1', '±èÁöÀ¯', '1995/12/25', 'GOLD');
INSERT INTO GIS_MEMBERS VALUES ( 'USER2', 'USERPW2', '±èÁ¤¼ö', '1991/10/20', 'BRONZE');
INSERT INTO GIS_MEMBERS VALUES ( 'USER3', 'USERPW3', '±èÇöÁø', '1991/8/5', 'SILVER');

SELECT * FROM GIS_MEMBERS;
SELECT * FROM GIS_MYPAGE;
SELECT * FROM GIS_TRAINING_DIARY;

DELETE FROM GIS_TRAINING_DIARY WHERE DIFFICULTY = 'D' OR DIFFICULTY = 'ÇÏ';

CREATE TABLE GIS_MYPAGE (
    MEMBER_CODE VARCHAR(30) CONSTRAINT GIS_MYPAGE_PK PRIMARY KEY,
    MEMBER_ID VARCHAR(30) CONSTRAINT GIS_MYPAGE_FK REFERENCES GIS_MEMBERS(MEMBER_ID),
    MEMBER_POINT NUMBER(10) CHECK (MEMBER_POINT >= 0),
    MEMBER_GOAL NUMBER(3) CHECK (MEMBER_GOAL BETWEEN 0 AND 100),
    MEMBER_STARTDATE DATE,
    MEMBER_ENDDATE DATE
);

INSERT INTO GIS_MYPAGE(MEMBER_CODE) VALUES('USERCODE1');
INSERT INTO GIS_MYPAGE(MEMBER_CODE) VALUES('USERCODE2');
INSERT INTO GIS_MYPAGE(MEMBER_CODE) VALUES('USERCODE3');

UPDATE GIS_MYPAGE
SET MEMBER_STARTDATE = '23/04/30', MEMBER_ENDDATE = '23/05/31'
WHERE MEMBER_ID = 'KKKKK';

COMMIT;



